# This file is generated by Anlogic Timing Wizard. 19 01 2020

#Created Clock
create_clock -name clk -period 8 -waveform {0 4} [get_nets {clk}]
create_clock -name clk_in -period 20 -waveform {0 10} [get_ports {clk_in}]

#Set False Path
set_false_path -from [get_clocks "clk"] -to [get_ports "clk_in"]
set_false_path -from [get_ports "clk_in"] -to [get_clocks "clk"]


