/************************************************************\
 **  Copyright (c) 2011-2021 Anlogic, Inc.
 **  All Right Reserved.
\************************************************************/
/************************************************************\
 ** Log	:	This file is generated by Anlogic IP Generator.
 ** File	:	E:/WORK/RISC_V_TEST/RISC_V/al_ip/ADC.v
 ** Date	:	2020 01 17
 ** TD version	:	4.2.285
\************************************************************/

`timescale 1ns / 1ps

module ADC ( eoc, dout, clk, pd, s, soc );
	output 		 eoc;
	output  		[11:0] dout;

	input  		clk;
	input  		pd;
	input  		[2:0] s;
	input  		soc;

	EG_PHY_ADC #(
		.CH7("ENABLE"),
		.CH6("ENABLE"),
		.CH4("ENABLE"),
		.CH3("ENABLE"),
		.CH2("ENABLE"),
		.CH1("ENABLE"),
		.CH0("ENABLE"))
		adc (
		.clk(clk),
		.pd(pd),
		.s(s),
		.soc(soc),
		.eoc(eoc),
		.dout(dout));

endmodule