/************************************************************\
 **  Copyright (c) 2011-2021 Anlogic, Inc.
 **  All Right Reserved.
\************************************************************/
/************************************************************\
 ** Log	:	This file is generated by Anlogic IP Generator.
 ** File	:	E:/WORK/RISC_V_TEST/RISC_V/al_ip/al_cpuregs.v
 ** Date	:	2020 01 17
 ** TD version	:	4.2.285
\************************************************************/

`timescale 1ns / 1ps

module al_cpureg ( 
	dia, addra, cea, clka, rsta, 
	dob, addrb, clkb, rstb
);

	output [31:0] dob;


	input  [31:0] dia;
	input  [5:0] addra;
	input  [5:0] addrb;
	input  cea;
	input  clka;
	input  clkb;
	input  rsta;
	input  rstb;




	EG_LOGIC_BRAM #( .DATA_WIDTH_A(32),
				.DATA_WIDTH_B(32),
				.ADDR_WIDTH_A(6),
				.ADDR_WIDTH_B(6),
				.DATA_DEPTH_A(64),
				.DATA_DEPTH_B(64),
				.MODE("PDPW"),
				.REGMODE_A("NOREG"),
				.REGMODE_B("NOREG"),
				.WRITEMODE_A("NORMAL"),
				.WRITEMODE_B("NORMAL"),
				.RESETMODE("SYNC"),
				.IMPLEMENT("9K(FAST)"),
				.INIT_FILE("NONE"),
				.FILL_ALL("NONE"))
			inst(
				.dia(dia),
				.dib({32{1'b0}}),
				.addra(addra),
				.addrb(addrb),
				.cea(cea),
				.ceb(1'b1),
				.ocea(1'b0),
				.oceb(1'b0),
				.clka(clka),
				.clkb(clkb),
				.wea(1'b1),
				.web(1'b0),
				.bea(1'b0),
				.beb(1'b0),
				.rsta(rsta),
				.rstb(rstb),
				.doa(),
				.dob(dob));


endmodule